[package]
name = "ar2300"
version = "0.1.0"
authors = ["Andrew Young <andrew@vaelen.org>"]
edition = "2018"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
rusb = "0.8"
simple-error = "0.2.3"
ctrlc = "3.1.9"
libusb1-sys = "0.5.0"