[package]
name = "ar2300-cli"
version = "0.1.0"
authors = ["Andrew Young <andrew@vaelen.org>"]
edition = "2018"

[dependencies]
ar2300 = { path = "lib" }
clap = "3.0.0-beta.4"
simple-error = "0.2.3"
ctrlc = "3.1.9"
tokio = { version = "1.11.0", features = ["full"] }